# Generated by Django 4.1.4 on 2023-01-05 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('phone_number', models.CharField(max_length=128, unique=True)),
                ('creation_date', models.DateField()),
                ('conclusion_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('city', models.CharField(max_length=128)),
                ('street', models.CharField(max_length=128)),
                ('house', models.CharField(max_length=128)),
                ('connection_date', models.DateField()),
                ('disconnection_date', models.DateField()),
                ('agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='connections.agreements')),
            ],
        ),
    ]
